// AUTO-GENERATED by server/scripts/gen_ts.py — do not edit by hand.
// Regenerate after any change to server/app/schemas/**.

export type Confidence = "verified" | "user_stated" | "parsed_unconfirmed";

/** Attached to every authored record. Derived layers carry their parent's. */
export interface Provenance {
  confidence: Confidence;
  source: Source;
  /** Set only by the human confirmation pass. None => never confirmed. */
  confirmed_at: string | null;
  updated_at: string | null;
}

export type Source = "user_entered" | "parsed_resume" | "parsed_linkedin" | "derived";

export interface Identity {
  legal_first: string;
  legal_middle: string | null;
  legal_last: string;
  /** What forms should show when they ask for a display name. */
  preferred_name: string | null;
  /** YYYY-MM-DD. Highest-sensitivity field in the system. */
  date_of_birth: string | null;
  /** ISO 3166-1 alpha-2 codes. Feeds ATTESTATION gating. */
  citizenship: string[];
  /** Self-identified only. Never inferred from a name. */
  pronouns: string | null;
  /** True once the user has confirmed. Writes then require an unlock. */
  locked: boolean;
  locked_at: string | null;
  provenance: Provenance;
}

export type AuthorizationStatus = "citizen" | "permanent_resident" | "visa" | "none" | "unknown";

export interface Links {
  linkedin: string | null;
  github: string | null;
  portfolio: string | null;
  other: Record<string, string>;
}

export interface Location {
  city: string | null;
  region: string | null;
  country: string | null;
  postal: string | null;
}

export interface Money {
  amount: number;
  currency: string;
  basis: string;
}

export interface Preferences {
  desired_comp: Money | null;
  notice_period_days: number | null;
  earliest_start: string | null;
  remote_preference: RemotePreference;
  willing_to_relocate: boolean | null;
}

export type RemotePreference = "onsite" | "hybrid" | "remote" | "no_preference";

/** NEVER inferred, NEVER generated, NEVER parsed from a resume. */
export interface WorkAuthorization {
  country: string | null;
  status: AuthorizationStatus;
  requires_sponsorship: boolean | null;
  work_permit_expiry: string | null;
  /** Pinned to USER_ENTERED. A parser must not write this. */
  source: Source;
  confirmed_at: string | null;
}

export interface Profile {
  email: string | null;
  /** E.164, e.g. +14155550123 */
  phone_e164: string | null;
  location: Location;
  links: Links;
  authorization: WorkAuthorization;
  preferences: Preferences;
  /** Dotted path -> last human confirmation. Drives staleness prompts. */
  confirmations: Record<string, string>;
  provenance: Provenance;
}

/** One bullet. Already atomic, so it maps 1:1 to an L3 chunk. */
export interface Achievement {
  id: string;
  text: string;
  skill_ids: string[];
  /** Extracted figures, e.g. ['40%', '$1.2M'] */
  metrics: string[];
}

export interface Credential {
  id: string;
  provenance: Provenance;
  /** Set when corrected. Superseded records are excluded from retrieval. */
  superseded_by: string | null;
  name: string;
  issuer: string;
  issued: string | null;
  expires: string | null;
  credential_id: string | null;
}

/** `end is None` means current. Drives recency ranking, so never omit it. */
export interface DateRange {
  /** YYYY-MM, normalized at ingest */
  start: string | null;
  /** YYYY-MM, or None for current */
  end: string | null;
}

export interface Education {
  id: string;
  provenance: Provenance;
  /** Set when corrected. Superseded records are excluded from retrieval. */
  superseded_by: string | null;
  institution: string;
  degree: string;
  field_of_study: string | null;
  dates: DateRange;
  /** None is MEANINGFUL — unknown, not zero. Routes to ATTESTATION. */
  gpa: number | null;
  honors: string[];
}

export interface Employment {
  id: string;
  provenance: Provenance;
  /** Set when corrected. Superseded records are excluded from retrieval. */
  superseded_by: string | null;
  employer: string;
  title: string;
  employment_type: EmploymentType;
  dates: DateRange;
  location: string | null;
  /** Role context for its achievements. */
  summary: string | null;
  achievements: Achievement[];
}

export type EmploymentType = "full_time" | "part_time" | "contract" | "internship" | "freelance" | "volunteer";

export interface Project {
  id: string;
  provenance: Provenance;
  /** Set when corrected. Superseded records are excluded from retrieval. */
  superseded_by: string | null;
  name: string;
  role: string | null;
  summary: string | null;
  dates: DateRange;
  skill_ids: string[];
  url: string | null;
  /** Parent employment, or None for personal. Attribution matters. */
  employer_id: string | null;
}

export interface Ledger {
  employment: Employment[];
  education: Education[];
  projects: Project[];
  credentials: Credential[];
}

export type EntityType = "employment_achievement" | "employment_summary" | "project" | "note";

export interface EvidenceChunk {
  chunk_id: string;
  text: string;
  entity_type: EntityType;
  /** Hard FK to the L2 record this came from. */
  entity_id: string;
  employer_id: string | null;
  /** Denormalized so it CANNOT be lost in the prompt. */
  employer_name: string | null;
  title_at_time: string | null;
  dates: DateRange;
  competency_tags: string[];
  skill_ids: string[];
  metrics: string[];
  lexical_terms: string[];
  /** None until Phase 1 dense retrieval lands. */
  embedding: number[] | null;
  confidence: Confidence;
  token_count: number;
  content_hash: string;
}

export type Retriever = "lexical" | "dense" | "competency_filter" | "fused";

/** A chunk plus why it was selected. This is what the trace viewer renders. */
export interface RetrievedChunk {
  chunk_id: string;
  score: number;
  retriever: Retriever;
  /** e.g. 'Acme Corp · Sr Eng · 2021-03 → 2023-06' */
  source_label: string;
  text_preview: string;
  competency_overlap: string[];
  rank_before_rerank: number | null;
}

export type Proficiency = "exposed" | "working" | "advanced" | "expert";

export type SkillKind = "hard" | "soft";

export interface SkillNode {
  id: string;
  name: string;
  /** ['ReactJS', 'React.js'] -> one node. */
  aliases: string[];
  kind: SkillKind;
  /** infra | language | tooling | domain … */
  category: string | null;
  years: number | null;
  /** YYYY-MM. Drives recency. */
  last_used: string | null;
  proficiency: Proficiency | null;
  /** Backing L3 chunks. Empty => a claim, not a fact. */
  evidence_ids: string[];
}

/** One requirement parsed out of a job description. */
export interface SkillDemand {
  raw_text: string;
  normalized_name: string;
  required_years: number | null;
  is_required: boolean;
}

/** The bridge between what the JD wants and what the user actually has. */
export interface SkillMatch {
  demand: SkillDemand;
  matched_skill_id: string | null;
  evidence_ids: string[];
  distance: number;
  /** Human-readable, e.g. 'adjacent: 3y Docker, no K8s' */
  rationale: string;
}

/** A soft skill, expressed as evidence rather than as a claim. */
export interface CompetencyNode {
  tag: string;
  label: string;
  evidence_ids: string[];
  strongest_chunk_id: string | null;
}

export interface CompetencyGraph {
  skills: SkillNode[];
  competencies: CompetencyNode[];
}

export type GenerationMode = "strict" | "optimize" | "aggressive";

export interface ApprovedAnswer {
  id: string;
  /** Stable ID from the question taxonomy. The lookup key. */
  canonical_question_id: string;
  /** Verbatim label as it appeared on the form. */
  raw_question: string;
  company_id: string | null;
  company_name: string | null;
  answer_text: string;
  char_count: number;
  mode_used: GenerationMode;
  evidence_ids_used: string[];
  /** True if the user changed the generated text. The signal worth mining. */
  edited_by_user: boolean;
  /** Kept when edited, so we can learn from the delta. */
  original_generated_text: string | null;
  approved_at: string;
  times_reused: number;
  embedding: number[] | null;
}

export interface AnswerMemory {
  answers: ApprovedAnswer[];
}

/** An AGGRESSIVE/OPTIMIZE claim, recorded with what it stretched from. */
export interface ClaimStretch {
  claim: string;
  /** Evidence chunk IDs. */
  backed_by: string[];
  distance: number;
  note: string | null;
}

export interface ClassifiedField {
  id: string;
  type: FieldType;
  context_label: string;
  constraints: Constraints;
  /** For select / radio. */
  options: string[];
  field_class: FieldClass;
  canonical_question_id: string | null;
  competency_tags: string[];
  /** 'attestation_denylist' | 'alias_dict' | 'adapter_map' | 'llm' | 'fail_closed' */
  classified_via: string;
  classifier_confidence: number;
  /** For DETERMINISTIC: the L0/L1/L2 key to read. */
  profile_path: string | null;
}

/** Extracted client-side, because a limit is a property of the page. */
export interface Constraints {
  max_value: number | null;
  min_value: number | null;
  unit: LimitUnit;
  is_required: boolean;
  /** 'maxLength' | 'placeholder' | 'helper_text' | 'counter' */
  extracted_from: string | null;
}

export type FieldClass = "deterministic" | "generative" | "attestation";

export type FieldType = "text" | "textarea" | "select" | "checkbox" | "radio" | "file" | "date" | "number" | "unknown";

/** A token in the output with no support in the passed evidence. */
export interface GroundingViolation {
  token: string;
  /** 'number' | 'proper_noun' | 'employer' | 'date' | 'credential' */
  kind: string;
  note: string | null;
}

export type LimitUnit = "chars" | "words" | "sentences";

export type Stage = "classify" | "answer_memory" | "retrieve" | "rerank" | "sufficiency_gate" | "generate" | "length_repair" | "ground_check";

export type StageStatus = "ok" | "hit" | "miss" | "skipped" | "abstained" | "stub" | "failed";

export interface TraceStep {
  stage: Stage;
  status: StageStatus;
  ms: number;
  tokens: number;
  cached_tokens: number;
  detail: string | null;
  chunks: RetrievedChunk[];
  violations: GroundingViolation[];
  skill_matches: SkillMatch[];
  /** Rendered prompt, so the viewer can show exactly what was sent. */
  prompt_preview: string | null;
}

export interface Trace {
  trace_id: string;
  created_at: string;
  mode: GenerationMode;
  field: ClassifiedField;
  jd_excerpt: string | null;
  steps: TraceStep[];
  /** None when the system abstained. */
  answer: string | null;
  chars: number;
  abstained: boolean;
  abstain_reason: string | null;
  needs_review: boolean;
  /** Max distance across all claims made. */
  claim_distance: number;
  /** Ceiling the mode allowed. */
  max_claim_distance: number;
  stretches: ClaimStretch[];
}

export interface AnswerRequest {
  question: string;
  mode: GenerationMode;
  jd_text: string | null;
  max_chars: number | null;
  field_type: string;
}

/** What GET /traces actually returns: Trace plus computed totals. */
export interface TraceView extends Trace {
  total_ms: number;
  total_tokens: number;
  cached_tokens: number;
}
