"""Generate TypeScript types from the Pydantic schema. One source of truth.

Two hand-maintained copies of this schema would drift within a week, and the
drift would be silent — the extension would send a field the server ignores.
Run this whenever `app/schemas/**` changes:

    python scripts/gen_ts.py

Output: viewer/src/types.generated.ts
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.schemas.answer_memory import AnswerMemory, ApprovedAnswer  # noqa: E402
from app.schemas.competency import CompetencyGraph, SkillMatch, SkillNode  # noqa: E402
from app.schemas.evidence import EvidenceChunk, RetrievedChunk  # noqa: E402
from app.schemas.identity import Identity  # noqa: E402
from app.schemas.ingest import ExtractionWarning, RawDocument  # noqa: E402
from app.schemas.ledger import Ledger  # noqa: E402
from app.schemas.profile import Profile  # noqa: E402
from app.pipeline.confirm import ConfirmRequest, ConfirmResult, Rejection  # noqa: E402
from app.schemas.session import AnsweredField, ApplicationSession  # noqa: E402
from app.schemas.structured import StructureResult, StructureWarning  # noqa: E402
from app.schemas.trace import AnswerRequest, Trace  # noqa: E402

EXPORTS = [
    Identity,
    Profile,
    Ledger,
    EvidenceChunk,
    RetrievedChunk,
    SkillNode,
    SkillMatch,
    CompetencyGraph,
    ApprovedAnswer,
    AnswerMemory,
    Trace,
    AnswerRequest,
    AnsweredField,
    ApplicationSession,
    ExtractionWarning,
    RawDocument,
    StructureWarning,
    StructureResult,
    Rejection,
    ConfirmRequest,
    ConfirmResult,
]

OUT = ROOT.parent / "viewer" / "src" / "types.generated.ts"

PRIMITIVES = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "null": "null",
}


def ts_type(node: dict, defs: dict) -> str:
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]

    if "enum" in node:
        return " | ".join(f'"{v}"' for v in node["enum"])

    if "anyOf" in node or "oneOf" in node:
        parts = [ts_type(s, defs) for s in node.get("anyOf") or node["oneOf"]]
        seen: list[str] = []
        for p in parts:
            if p not in seen:
                seen.append(p)
        return " | ".join(seen)

    t = node.get("type")
    if t == "array":
        items = node.get("items")
        return f"{ts_type(items, defs)}[]" if items else "unknown[]"
    if t == "object":
        extra = node.get("additionalProperties")
        if isinstance(extra, dict):
            return f"Record<string, {ts_type(extra, defs)}>"
        return "Record<string, unknown>"
    if isinstance(t, list):
        return " | ".join(PRIMITIVES.get(x, "unknown") for x in t)
    if t in PRIMITIVES:
        return PRIMITIVES[t]
    return "unknown"


def render_interface(name: str, schema: dict, defs: dict) -> str:
    if "enum" in schema:
        values = " | ".join(f'"{v}"' for v in schema["enum"])
        return f"export type {name} = {values};\n"

    lines = [f"export interface {name} {{"]

    if schema.get("description"):
        lines.insert(0, f"/** {schema['description'].splitlines()[0]} */")

    # Every field is emitted as PRESENT, because `model_dump()` always includes
    # it — a Pydantic default means "you don't have to send it", not "it may be
    # missing from the response". Nullability comes from the declared type alone,
    # so `steps: TraceStep[]` stays a plain array instead of degrading into
    # `TraceStep[] | null | undefined` and forcing guards at every call site.
    for prop, spec in (schema.get("properties") or {}).items():
        doc = spec.get("description")
        if doc:
            lines.append(f"  /** {doc.splitlines()[0]} */")
        lines.append(f"  {prop}: {ts_type(spec, defs)};")

    lines.append("}\n")
    return "\n".join(lines)


def main() -> None:
    chunks: list[str] = [
        "// AUTO-GENERATED by server/scripts/gen_ts.py — do not edit by hand.",
        "// Regenerate after any change to server/app/schemas/**.",
        "",
    ]
    emitted: set[str] = set()

    for model in EXPORTS:
        schema = model.model_json_schema(ref_template="#/$defs/{model}")
        defs = schema.pop("$defs", {})

        for def_name, def_schema in defs.items():
            if def_name in emitted:
                continue
            emitted.add(def_name)
            chunks.append(render_interface(def_name, def_schema, defs))

        name = schema.get("title", model.__name__)
        if name not in emitted:
            emitted.add(name)
            chunks.append(render_interface(name, schema, defs))

    # Computed properties the API flattens in via `Trace.model_dump_view()`.
    chunks.append(
        "\n".join(
            [
                "/** What GET /traces actually returns: Trace plus computed totals. */",
                "export interface TraceView extends Trace {",
                "  total_ms: number;",
                "  total_tokens: number;",
                "  cached_tokens: number;",
                "}",
                "",
                "/** What the /ingest endpoints return: RawDocument plus computed counts. */",
                "export interface DocumentView extends RawDocument {",
                "  char_count: number;",
                "  word_count: number;",
                "  line_count: number;",
                "  is_usable: boolean;",
                "}",
                "",
                "/** What the /structure endpoints return: StructureResult plus counts. */",
                "export interface StructureView extends StructureResult {",
                "  record_count: number;",
                "  achievement_count: number;",
                "  /** Achievements not found in the source. Non-zero means review carefully. */",
                "  unverified_quotes: number;",
                "  blocking: StructureWarning[];",
                "}",
                "",
                "/** What POST /confirm returns: ConfirmResult plus the resulting memory stats. */",
                "export interface ConfirmView extends ConfirmResult {",
                "  records_committed: number;",
                "  memory: Record<string, unknown>;",
                "}",
                "",
            ]
        )
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(chunks), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT.parent)} ({len(emitted)} types)")


if __name__ == "__main__":
    main()
